"""Add AuditLog table for Fishmonger Tuning

Revision ID: 62a50104f40b
Revises: 8fb2bf48f188
Create Date: 2025-12-13 02:51:19.752747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a50104f40b'
down_revision: Union[str, Sequence[str], None] = '8fb2bf48f188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('original_section', sa.String(), nullable=True),
    sa.Column('final_section', sa.String(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('modifier_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
