"""add perf_metrics to run

Revision ID: 8fb2bf48f188
Revises: dc334ba6b3ae
Create Date: 2025-12-12 18:35:22.088288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb2bf48f188'
down_revision: Union[str, Sequence[str], None] = 'dc334ba6b3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('perf_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'perf_metrics')
    # ### end Alembic commands ###
