"""create run and run_articles tables

Revision ID: 91f37b865042
Revises: a3e337266b56
Create Date: 2025-12-12 15:14:33.789366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f37b865042'
down_revision: Union[str, Sequence[str], None] = 'a3e337266b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('stats_input', sa.Integer(), nullable=True),
    sa.Column('stats_pool', sa.Integer(), nullable=True),
    sa.Column('stats_qualified', sa.Integer(), nullable=True),
    sa.Column('stats_selected', sa.Integer(), nullable=True),
    sa.Column('source_dominance', sa.JSON(), nullable=True),
    sa.Column('cut_line_report', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('article_id', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_articles')
    op.drop_table('runs')
    # ### end Alembic commands ###
