"""create articles table

Revision ID: a3e337266b56
Revises: 
Create Date: 2025-12-12 14:12:46.600759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e337266b56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('comments_url', sa.String(), nullable=True),
    sa.Column('comments_full', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('stats_score', sa.Integer(), nullable=True),
    sa.Column('stats_comments', sa.Integer(), nullable=True),
    sa.Column('is_enhanced', sa.Boolean(), nullable=True),
    sa.Column('computed_score', sa.Float(), nullable=True),
    sa.Column('computed_category', sa.String(), nullable=True),
    sa.Column('computed_breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_debug', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_articles_external_id'), 'articles', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_external_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
