"""add index to article timestamp

Revision ID: dc334ba6b3ae
Revises: 91f37b865042
Create Date: 2025-12-12 18:32:53.035980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc334ba6b3ae'
down_revision: Union[str, Sequence[str], None] = '91f37b865042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_timestamp'), 'articles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_timestamp'), table_name='articles')
    # ### end Alembic commands ###
